sudo: required
language: generic

services:
          - docker

before_install:
          - docker build -t rajahuja/docker_react -f Dockerfile.dev .

script:
          - docker run -e CI=true rajahuja/docker_react npm run test
